In [144]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
import numpy as np
import math

In [153]:
digits = load_digits()
minibatchsize = 5
target_size = len(digits.target_names)
print(target_size)

X = np.array(digits.data)
y = np.array(digits.target)

# scaling the numbers
X = (X - np.min(X))/(np.max(X)-np.min(X))

# float 64 shoudl be fine aswell
print(X.dtype)

# encoding into one hot vectors
y = np.eye(target_size)[y]

# helper function to confirm correct splitting
def show_img(digits):
  plt.gray()
  plt.matshow(digits.reshape(8, 8))
  plt.show()

# yield X, y randomly
def shuffle_generator(X, y, minibatchsize=minibatchsize):
  shuffler = np.random.permutation(len(X))
  X = X[shuffler]
  y = y[shuffler]
  start_index = 0

  while start_index + minibatchsize < len(X):
    yield(X[start_index:start_index+minibatchsize], y[start_index:start_index+minibatchsize])
    start_index += minibatchsize

10
float64


In [173]:
class sigmoid_function():
  # minibatchsize, 64
  def __call__(self, input : np.ndarray):
    out = 1/(1 + np.exp(-input))
    return out

  # preactivation: (minibatch_size, num_units)
  def backwards(preactivation, activation, error):
    # calculate: dL/d_preactivation
    pass


class softmax():
  # minibatchsize, 10
  def __call__(self, input : np.ndarray):
    output = np.ndarray(shape=(minibatchsize, target_size), dtype=float)
    for idx, batch in enumerate(input):
      sum = np.sum(np.exp(batch))
      out = np.exp(batch) / sum
      output[idx] = out
    return output

class cross_entropy():
  # beide 10 groß
  def __call__(y_true : np.ndarray, y_pred : np.ndarray):
    return -np.sum(y_true * np.log(y_pred + 10**-100))

  def backwards(prediction : np.ndarray, target : np.ndarray, loss : float):
    return prediction - target


act_fct = sigmoid_function()
soft = softmax()
gen = shuffle_generator(X, y)

X_batch, y_batch = next(gen)

print(y_batch)

act_X = act_fct(X_batch)
sof_y = soft(y_batch)

print(sof_y.shape)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(5, 10)


In [185]:
from typing import List

class MLP_layer():
  def __init__(self, activation_function : any, units : int, input_size : int):
    self.activation_function = activation_function
    self.units = units
    self.input_size = input_size
    self.weights = np.random.normal(0, 0.2, size=(units, input_size))
    self.bias = np.zeros(units)

  def forward(self, input : np.ndarray):
    output = np.ndarray(shape=(minibatchsize, self.units), dtype=float)

    for idx, input in enumerate(input):
      new_unit_values = self.weights @ input
      output[idx] = new_unit_values

    output = output - self.bias
    output = self.activation_function(output)
    return output

class ANN():
  def __init(self):
    layer1 = MLP_layer(sigmoid_function(), 32, 64)
    layer2 = MLP_layer(sigmoid_function(), 16, 32)
    layer3 = MLP_layer(softmax(), 10, 16)
    self.layers = [layer1, layer2, layer3]

# Implement the backwards function for your CCE object: It expects at least
# the inputs prediction (our ˆy) of shape (minibatch size,10), and loss (our LCCE of
# shape (minibatch size,1), i.e. one loss per minibatch element. It should return
# a respective matrix of shape (minibatch size,1) representing the error signal
# (think in Leibnitz notation: The derivative calculated up to this step).







print(output1)


[[0.70968288 0.67193585 0.60429279 0.42634499 0.30809749 0.58250221
  0.42753085 0.57189351 0.52548654 0.38878332 0.21356587 0.52279922
  0.75422911 0.80538153 0.38797798 0.39687768 0.20465349 0.57146999
  0.5456352  0.39139718 0.4952512  0.68851924 0.56431047 0.42988551
  0.77647086 0.49822981 0.42725605 0.68478528 0.40847654 0.46694883
  0.59594611 0.58653055]
 [0.72616556 0.68784906 0.42248407 0.52007674 0.1883039  0.46374787
  0.36625387 0.3497367  0.57676841 0.41630507 0.26909414 0.62756116
  0.65282495 0.86173109 0.27560076 0.24702721 0.46872244 0.66395392
  0.59375255 0.55514425 0.5002546  0.61099833 0.33683589 0.42382507
  0.71682994 0.51722408 0.5194866  0.84695919 0.34750508 0.45804091
  0.52847793 0.44754943]
 [0.58971917 0.64002387 0.74114231 0.56033035 0.39978236 0.68775009
  0.51179405 0.57131789 0.61633504 0.25508806 0.1491633  0.53552062
  0.79221174 0.72838516 0.33866816 0.39781363 0.18467192 0.76450513
  0.65781593 0.37633224 0.54319054 0.70945722 0.69126984 0.6274175